"""catalogue: categories, products, product images

Revision ID: 812bf517d686
Revises: ceff460d10dc
Create Date: 2026-09-19 15:14:16.009953

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "812bf517d686"
down_revision: str | None = "ceff460d10dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# The category list Kumaran Crackers opens with. Ordered as they appear on the
# customer home screen.
STARTER_CATEGORIES: list[dict[str, object]] = [
    {
        "name": "Sparklers",
        "slug": "sparklers",
        "display_order": 1,
        "description": "Hand-held sparklers for every celebration.",
    },
    {
        "name": "Rockets",
        "slug": "rockets",
        "display_order": 2,
        "description": "Classic aerial rockets.",
    },
    {
        "name": "Flower Pots",
        "slug": "flower-pots",
        "display_order": 3,
        "description": "Ground fountains that bloom into colour.",
    },
    {
        "name": "Chakkars",
        "slug": "chakkars",
        "display_order": 4,
        "description": "Spinning ground wheels.",
    },
    {
        "name": "Fancy Crackers",
        "slug": "fancy-crackers",
        "display_order": 5,
        "description": "Novelty and speciality crackers.",
    },
    {
        "name": "Ground Crackers",
        "slug": "ground-crackers",
        "display_order": 6,
        "description": "Traditional ground crackers and bombs.",
    },
    {
        "name": "Combo Packs",
        "slug": "combo-packs",
        "display_order": 7,
        "description": "Value combinations at a bundled price.",
    },
    {
        "name": "Gift Packs",
        "slug": "gift-packs",
        "display_order": 8,
        "description": "Curated assortments, ready to gift.",
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    categories_table = op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_index(
        op.f("ix_categories_display_order"), "categories", ["display_order"], unique=False
    )
    op.create_index(op.f("ix_categories_is_active"), "categories", ["is_active"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("mrp", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("selling_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("stock_quantity", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "low_stock_threshold", sa.Integer(), server_default=sa.text("10"), nullable=False
        ),
        sa.Column("sold_quantity", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "low_stock_threshold >= 0", name=op.f("ck_products_threshold_non_negative")
        ),
        sa.CheckConstraint("mrp >= 0", name=op.f("ck_products_mrp_non_negative")),
        sa.CheckConstraint(
            "selling_price <= mrp", name=op.f("ck_products_selling_price_not_above_mrp")
        ),
        sa.CheckConstraint(
            "selling_price >= 0", name=op.f("ck_products_selling_price_non_negative")
        ),
        sa.CheckConstraint(
            "sold_quantity >= 0", name=op.f("ck_products_sold_quantity_non_negative")
        ),
        sa.CheckConstraint("stock_quantity >= 0", name=op.f("ck_products_stock_non_negative")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_products_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(
        "ix_products_category_active", "products", ["category_id", "is_active"], unique=False
    )
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(op.f("ix_products_is_active"), "products", ["is_active"], unique=False)
    op.create_index(op.f("ix_products_is_featured"), "products", ["is_featured"], unique=False)
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_index(op.f("ix_products_slug"), "products", ["slug"], unique=True)
    op.create_table(
        "product_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=500), nullable=False),
        sa.Column("alt_text", sa.String(length=200), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_images_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_images")),
    )
    op.create_index(
        op.f("ix_product_images_product_id"), "product_images", ["product_id"], unique=False
    )
    op.create_index(
        "uq_product_images_one_primary",
        "product_images",
        ["product_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )

    # ---- Seed the starting catalogue -------------------------------------
    # Unlike roles, these are ordinary business data: the admin may rename,
    # reorder, deactivate or delete any of them after deployment.
    op.bulk_insert(categories_table, STARTER_CATEGORIES)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_product_images_one_primary",
        table_name="product_images",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_index(op.f("ix_product_images_product_id"), table_name="product_images")
    op.drop_table("product_images")
    op.drop_index(op.f("ix_products_slug"), table_name="products")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_is_featured"), table_name="products")
    op.drop_index(op.f("ix_products_is_active"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_index("ix_products_category_active", table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_is_active"), table_name="categories")
    op.drop_index(op.f("ix_categories_display_order"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
